ChaptersToCue: Add TaglibSharp ProjectReference
So far, CUETools.ChaptersToCue.csproj contained a Reference to
TaglibSharp with a HintPath to TagLibSharp.dll. This has worked
in VS2017 or VS2019. However, in VS2022 a build error occurs during
the first attempt of building the Solution.

- CUETools.ChaptersToCue.csproj:
  Add ProjectReference to TaglibSharp
- Fixes the following errors, when building using VS2022:
  Error CS0246 The type or namespace name 'TagLib' could not be found
    (are you missing a using directive or an assembly reference?)
    CUETools.ChaptersToCue\Program.cs
  Error CS0103 The name 'TagLib' does not exist in the current context
    CUETools.ChaptersToCue\Program.cs